# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amortecedor',
            fields=[
                ('amortecedor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Amortecedor')),
                ('amortecedor_codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('amortecedor_diametro_externo', models.IntegerField(verbose_name='Tamanho do Diâmetro Externo')),
                ('amortecedor_curso', models.IntegerField(verbose_name='Tamanho do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('teste_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('teste_nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('teste_quantidade_ciclo', models.IntegerField(null=True, verbose_name='Quantidade de Ciclo')),
                ('teste_observacoes', models.TextField(max_length=255, null=True, verbose_name='Observações')),
                ('teste_data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='TesteTemperatura',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Teste')),
                ('testeTT_quantidade_temperatura', models.IntegerField(null=True, verbose_name='Quantidade de Temperaturas')),
                ('testeVV_quantidade_velocidade', models.IntegerField(null=True, verbose_name='Quantidade de Velocidades')),
            ],
            bases=('app.teste',),
        ),
        migrations.CreateModel(
            name='TesteVelocidadeFixa',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Teste')),
                ('testeVF_velocidade', models.IntegerField(null=True, verbose_name='Velocidade do Motor')),
            ],
            bases=('app.teste',),
        ),
        migrations.CreateModel(
            name='TesteVelocidadeVariavel',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Teste')),
                ('testeVV_quantidade_velocidade', models.IntegerField(null=True, verbose_name='Quantidade de Velocidades')),
            ],
            bases=('app.teste',),
        ),
        migrations.AddField(
            model_name='grafico',
            name='teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teste', verbose_name='Teste'),
        ),
        migrations.AddField(
            model_name='amortecedor',
            name='testes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teste', verbose_name='Testes'),
        ),
    ]
