# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('teste_id', models.AutoField(primary_key=True, serialize=False)),
                ('teste_nome', models.CharField(max_length=45, null=True)),
                ('teste_tempo_total', models.TimeField(null=True)),
                ('teste_tempo_oscilacao', models.TimeField(null=True)),
                ('teste_observacoes', models.TextField(max_length=255, null=True)),
                ('teste_data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
