# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 11:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='graficoForcaTempo',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='graficoMimimi',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teste',
            name='graficoTemperatura',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='testevelocidadevariavel',
            name='arrayVelocidades',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='teste_quantidade_ciclo',
            field=models.IntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Ciclo'),
        ),
        migrations.AlterField(
            model_name='testevelocidadefixa',
            name='testeVF_velocidade',
            field=models.IntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Velocidade do Motor'),
        ),
    ]
